/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import ipc1.proyect2.Actividad;
import ipc1.proyect2.Curso;
import ipc1.proyect2.AppState;
import ipc1.proyect2.Estudiantes;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;

/**
 *
 * @author danis
 */
public class CursoJFrame extends JFrame {

	public Curso curso;

    /**
     * Creates new form CursoJFrame
     */
    public CursoJFrame(Curso curso) {
				this.curso = curso;
        initComponents();
        
        this.setVisible(true); // Hace visible la ventana
        this.setLocationRelativeTo(null); // La coloca al centro
        this.setResizable(false); // Bloquea el redimensionamiento de la ventana
        this.setTitle(curso.nombre); // Coloca un titulo a la ventana
        
        this.llenartablaact();
        
        this.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosing(WindowEvent e) {
               AppState.serializar();
           }
        });
    }
    
    public void llenartablaact(){
        int tamano = curso.actividades.size();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount(tamano);
        // Se agregaran las columnas
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Ponderacion");
        modelo.addColumn("Promedio");
        //datos
        for(int i = 0; i < tamano; i++){
            Actividad actividad = Curso.actividades.get(i);
            modelo.setValueAt(actividad.getNombre(), i, 0);
            modelo.setValueAt(actividad.getDescripcion(), i, 1);
            modelo.setValueAt(actividad.getPonderacion(), i, 2);
            modelo.setValueAt("", i, 3);
        }
        this.ActividadesjTable1.setModel(modelo);
    }
    
    /*public void Crearbotoncurso(){
       int coordenadaX = 200;
       int coordenadaY = 200;
	int anchoBoton = 100;
	int altoBoton = 50;
       //for(Curso curso: AppState.cursos){
	//Profesores profesor = AppState.findProfesor(curso.codigoProfesor);
	//if(profesor != null){
	JButton botoncurso = new JButton("Acciones"); 
	botoncurso.setBounds(coordenadaX, coordenadaY, anchoBoton, altoBoton);
	//Agregar accion
	botoncurso.addActionListener(new ActionListener() {
	 @Override
	  public void actionPerformed(ActionEvent e) {
                       CursoJFrame cursoJFrame = new CursoJFrame(curso);
                   }
               });

               this.add(botoncurso);
               //coordenadaX += 120;
           //}
       //}
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlumnosjTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CargamasivaalumnosjButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MRendimientoestujButton1 = new javax.swing.JButton();
        PrendimientoestujButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ActividadesjTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombreact = new javax.swing.JTextField();
        txtdesccurso = new javax.swing.JTextField();
        txtponderacioncur = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Listado de alumnos");

        AlumnosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AlumnosjTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText(curso.nombre);

        CargamasivaalumnosjButton1.setText("Carga Masiva Alumnos");
        CargamasivaalumnosjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargamasivaalumnosjButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Reportes");

        MRendimientoestujButton1.setText("Top 5 - Estudientes con Mejor Rendimiento");

        PrendimientoestujButton2.setText("Top 5 - Estudientes con Peor Rendimiento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Actividades");

        ActividadesjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción", "Ponderación", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ActividadesjTable1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Crear Actividad");

        jLabel6.setText("Nombre");

        jLabel7.setText("Descripción");

        jLabel8.setText("Ponderació");

        jLabel9.setText("Notas");

        jButton1.setText("Seleccionar archivo CSV");

        jButton2.setText("Crear Actividad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(CargamasivaalumnosjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MRendimientoestujButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(PrendimientoestujButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombreact)
                            .addComponent(txtdesccurso)
                            .addComponent(txtponderacioncur)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnombreact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtdesccurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CargamasivaalumnosjButton1)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtponderacioncur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jButton1)
                            .addComponent(MRendimientoestujButton1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(PrendimientoestujButton2)))
                    .addComponent(jLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargamasivaalumnosjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargamasivaalumnosjButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
						  fileChooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter csvFilter = new FileNameExtensionFilter("Archivos CSV", "csv");
        fileChooser.setFileFilter(csvFilter);

        int fileChooserState = fileChooser.showOpenDialog(this);
        if (fileChooserState == JFileChooser.APPROVE_OPTION) {
            File[] archivos = fileChooser.getSelectedFiles();
            for (File file : archivos) {
                try {
                    BufferedReader reader = new BufferedReader(new FileReader(file));
                    String linea;

                    while ((linea = reader.readLine()) != null) {
                        String[] datos = linea.split(",");
                        String codigoestu = datos[0];
                        /*String nombreestu = datos[1];
                        String apellidoestu = datos[2];
                        String correoestu = datos[3];
                        String generoestu = datos[4];*/
                        //Se agrega a profesores
                        for(int i = 0; i<AppState.getEstudiantes().size();i++){
                            Estudiantes actu = AppState.getEstudiantes().get(i);
                            if(actu.getCodigoe().equals(codigoestu)){
                                Estudiantes estudiante = new Estudiantes(codigoestu, actu.getNombree(),
                                        actu.getApellidoe(), "", "", 
                                        "", "", "");
                            }
                        }
                        /*Estudiantes estudiante = new Estudiantes(
                                codigoestu, nombreestu, apellidoestu,
                                correoestu, "1234", generoestu,
                                codigoestu, "1234"
                        );
                        AppState.addEstudiante(estudiante);
                        curso.addEstudiante(estudiante.codigoe);*/
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                    System.out.println("Error al Cargar Archivo");
                }
            }
            llenartablaalumnos();
        }
    }//GEN-LAST:event_CargamasivaalumnosjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Actividad actividad = new Actividad("", txtnombreact.getText(),
                txtdesccurso.getText(), txtponderacioncur.getText(), "");
        Curso.actividades.add(actividad);
        
        this.llenartablaact();
    }//GEN-LAST:event_jButton2ActionPerformed

	public void llenartablaalumnos(){
	 int tamano = AppState.getEstudiantes().size();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount(tamano);
        // Se agregaran las columnas
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Acciones");
        //datos
        for(int i = 0; i < tamano; i++){
            Estudiantes estudiantes = AppState.getEstudiantes().get(i);
            modelo.setValueAt(estudiantes.getCodigoe(), i, 0);
            modelo.setValueAt(estudiantes.getNombree(), i, 1);
            modelo.setValueAt(estudiantes.getApellidoe(), i, 2);
            modelo.setValueAt("", i, 3);
        }
        this.AlumnosjTable1.setModel(modelo);
    }
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActividadesjTable1;
    private javax.swing.JTable AlumnosjTable1;
    private javax.swing.JButton CargamasivaalumnosjButton1;
    private javax.swing.JButton MRendimientoestujButton1;
    private javax.swing.JButton PrendimientoestujButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtdesccurso;
    private javax.swing.JTextField txtnombreact;
    private javax.swing.JTextField txtponderacioncur;
    // End of variables declaration//GEN-END:variables
}
